[build]
  command = "npm run build:production"
  publish = "dist"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/og-preview.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "image/png"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"
